### ISSUE TITLE
Setup Donate Card Grid on new Donate Page

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/next-website-v2#213] opened 2024-11-12 00:19 UTC
**Design:** [See this Figma file.](https://www.figma.com/design/Yq8LKeIVka701hYL45heud/Colors-for-DA?node-id=181-9119&m=dev)

![Screenshot from 2024-11-11 23 31 01@2x](https://github.com/user-attachments/assets/90c5b052-020c-41e5-ac03-d8f7ef21bec7)

**Code:**

- See `src/app/donate/new-donate` for the space we're working on the new donate page at.
- The current donate page is in `src/app/donate` but this design marks a significant departure from it.
- See `src/components/donate` for donate-specific components.  It's ok to mix new and old components in here- we'll remove the old when we replace the current donate page with the new one.
- Checkout how [Radix UI layout](https://www.radix-ui.com/themes/docs/overview/layout) works, and related components like [Flex](https://www.radix-ui.com/themes/docs/components/flex) or [Grid](https://www.radix-ui.com/themes/docs/components/grid).

**Notes:**

- Since we're making a new page with a significantly different design than the old one, there shouldn't need to be too much code reuse.  Let's prioritize using [Radix UI](https://www.radix-ui.com/) components (check both their [Theme](https://www.radix-ui.com/themes/docs/overview/getting-started) and [Primitives](https://www.radix-ui.com/primitives/docs/overview/introduction) docs).  It's ok to sprinkle in some tailwind in order to go above and beyond what we get out of the box with Radix, but don't feel like you need to be pixel-perfect when following the designs.

**Comment by jtfairbank** [comment] 2024-11-12 00:27
@hcavanaugh maybe a good next issue for you, since your last PR included a change to the donate card image?

**Comment by Hieu4short** [comment] 2024-11-12 08:47
Hi, can I help you fulfilling this project?

**Comment by jtfairbank** [comment] 2024-11-12 12:37
Hey @Hieu4short could you email `tech @ distributeaid . org` to introduce yourself?  We're primarily looking for contributors with existing webdev experience at the moment, so please be sure to highlight that.  If you're looking for a way to gain experience doing web development, our [Open Source Explorers](https://distributeaid.org/tech/oss-explorers/) program may be a better fit. :smile:

**Comment by jtfairbank** [comment] 2024-11-21 18:50
Go for it!!

**Comment by Huiclaire** [comment] 2024-11-22 14:50
Hi @jtfairbank 

I just realized I left my message in the wrong issue! I actually meant to pick up [issue #91](https://github.com/distributeaid/next-website-v2/issues/91), as this one is already assigned. Apologies for the confusion!

**Comment by hcavanaugh** [comment] 2024-11-23 04:56
Hey @jtfairbank , no worries, but now I'm confused. Is this task a duplicate of #91?

**Comment by jtfairbank** [comment] 2024-11-23 05:31
@hcavanaugh no!  This one is focused on the grid of multiple cards, #91 is focused on the card itself. :smile:

**Closed** 2024-12-06 00:21 UTC
Labels: enhancement, good first issue
